# Generated by Django 4.1.7 on 2023-08-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_orderitem_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
