# Generated by Django 4.1.7 on 2023-09-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_orderitem_price_alter_product_digital_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
