# Generated by Django 4.1.7 on 2023-09-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_product_description_alter_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="combo",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
