# Generated by Django 4.1.7 on 2023-10-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_product_combo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
