# Generated by Django 4.1.7 on 2023-10-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_customer_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="orderItems",
            field=models.ManyToManyField(through="store.OrderItem", to="store.product"),
        ),
    ]
