# Generated by Django 4.1.7 on 2023-10-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_remove_order_orderitems"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="phone",
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
